spring:
#  activiti:
#    #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
#    spring.activiti.check-process-definitions: false
#    #true，会对数据库所有表进行更新，若表不存在就会自动创建，默认false，启动时会进行对比，错误会抛出异常
#    database-schema-update: true
#    #保存历史数据级别设置为full最高级别，便于历史数据的追溯,一共有四个值
#    # none 不报错历史数据，效率高
#    # activity 级别高于none，保存流程实例与流程行为，其他数据不保存
#    # audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值
#    # full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等
#    history-level: full
  datasource:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 5
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 5
      maxWait: 60000
      poolPreparedStatements: true
      filters: stat,wall
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/huang?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      maxPoolPreparedStatementPerConnectionSize: 20
      username: root
      password: 123456
      testOnBorrow: false
      testWhileIdle: true
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      driver-class-name: com.mysql.cj.jdbc.Driver
      maxActive: 50



server:
  port:8081
logging:
  pattern:
    console: "%d{yyyy-MM-dd: mm:ss.SSS} %-5level [%logger{36}] :   %msg%n"
  level:
    org:
      springframework:
        web: debug